repo_url: https://github.com/Interacao-Humano-Computador/2024.1-Grupo01
repo_name: 2024.1-Grupo01

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

site_name: Grupo 01


nav:
  - Inicio: 
      - Inicio: index.md
      - Licença: licenca.md
  - Apresentações:
      - Apresentação 1: apresentacao/apresentacao1.md
      - Apresentação 2: apresentacao/apresentacao2.md
      - Apresentação 3: apresentacao/apresentacao3.md
      - Apresentação 4: apresentacao/apresentacao4.md
      - Apresentação 5: apresentacao/apresentacao5.md
  - Reuniões:
      - Reunião 1: reuniao/reuniao01.md
      - Reunião 2: reuniao/reuniao02.md
      - Reunião 3: reuniao/reuniao03.md
      - Reunião 4: reuniao/reuniao04.md
  - Planejamento:
    - Cronograma: planejamento/cronograma.md
    - Heatmap: planejamento/heatmap.md
    - Ferramentas: planejamento/ferramentas.md
    - Metodologia: planejamento/metodologia.md
    - Processos de Design: planejamento/processosDesign.md
    - Sites Avaliados: planejamento/sitesAvaliados.md
    - Site Escolhido: planejamento/siteEscolhido.md
  - Analise de Requisitos:
    - Aspectos Éticos: analise-de-requisitos/aspectosEticos.md
    - Análise de Tarefas:
      - Análise Hierárquica de Tarefas: analise-de-requisitos/analise-de-tarefas/analiseHierarquicaTarefa.md
      - GOMS: analise-de-requisitos/analise-de-tarefas/GOMS.md
    - Perfil de Usuário: analise-de-requisitos/perfildeUsuario.md
    - Personas: analise-de-requisitos/personas.md
    - Guia de Estilo: analise-de-requisitos/guiaEstilo.md
    - Cenários: analise-de-requisitos/cenario.md
    - Princípios Gerais: analise-de-requisitos/principios.md
    - Metas de Usabilidade: analise-de-requisitos/metasDeUsabilidade.md
    - Caracteristicas da plataforma: analise-de-requisitos/caracteristicasPlataforma.md
  - Design, Avaliação e Desenvolvimento:
    - Nível 1:
      - Análise de Tarefas: 
        - Planejamento da Avaliação: design-avaliacao-desenvolvimento/nivel1/analiseTarefas/planejamentoAvaliacao.md
        - Planejamento do Relato dos Resultados da Avaliação: design-avaliacao-desenvolvimento/nivel1/analiseTarefas/planejamentoRelatoResultadoAnaliseTarefas.md
        - Relatos dos Resultados: design-avaliacao-desenvolvimento/nivel1/analiseTarefas/relatosResultados.md
      - Storyboard:
        - Planejamento da Avaliação: design-avaliacao-desenvolvimento/nivel1/storyboard/planejamentoAvaliacao.md
        - Storyboards: design-avaliacao-desenvolvimento/nivel1/storyboard/storyboards.md
        - Planejamento do Relato dos Resultados da Avaliação: design-avaliacao-desenvolvimento/nivel1/storyboard/planejamentoRelatoResultadoStoryboard.md
        - Relatos dos Resultados: design-avaliacao-desenvolvimento/nivel1/storyboard/relatosResultados.md
    - Nivel 2:
      - Protótipo de Papel:
        - Planejamento da Avaliação do Protótipo de Papel: design-avaliacao-desenvolvimento/nivel2/prototipoPapel/planejamentoAvaliacao.md
        - Planejamento do Relato dos Resultados da Avaliação: design-avaliacao-desenvolvimento/nivel2/prototipoPapel/planejamentoResultados.md



theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:

    # Palette toggle for automatic mode
   # - media: "(prefers-color-scheme)"
     # toggle:
     #   icon: material/brightness-auto
     #   name: Mudar para o modo claro

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Mudar para a preferência do sistema

  language: pt-BR
  favicon: assets/logoMoj.png
  logo: assets/logoMoj.png

extra:
  version:
    provider: mike

extra_css: [stylesheets/style.css]
